### ISSUE TITLE
Failing tests cause a double refresh error on the spring context

### ISSUE THREAD

**Issue by stickycode** [StickySource/sticky-mockwire-spring3#1]
java.lang.AssertionError: java.lang.IllegalStateException: GenericApplicationContext does not support multiple refresh attempts: just call 'refresh' once
	at net.stickycode.mockwire.junit4.MockwireContainerLifecycleStatement.shutdown(MockwireContainerLifecycleStatement.java:37)
	at net.stickycode.mockwire.junit4.MockwireContainerLifecycleStatement.evaluate(MockwireContainerLifecycleStatement.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.lang.IllegalStateException: GenericApplicationContext does not support multiple refresh attempts: just call 'refresh' once
	at org.springframework.context.support.GenericApplicationContext.refreshBeanFactory(GenericApplicationContext.java:241)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:542)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:451)
	at net.stickycode.bootstrap.spring3.Spring3StickyBootstrap.getContext(Spring3StickyBootstrap.java:78)
	at net.stickycode.bootstrap.spring3.Spring3StickyBootstrap.find(Spring3StickyBootstrap.java:92)
	at net.stickycode.bootstrap.spring3.Spring3StickyBootstrap.shutdown(Spring3StickyBootstrap.java:127)
	at net.stickycode.mockwire.MockwireBootstrap.shutdown(MockwireBootstrap.java:39)
	at net.stickycode.mockwire.junit4.MockwireContainerLifecycleStatement.shutdown(MockwireContainerLifecycleStatement.java:34)
	... 16 more

**Comment by stickycode** [comment]
Resolved for spring3, pending spring4
